// <auto-generated />
using System;
using LearningPlatform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningPlatform.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260902204351_AddTopicMaterialMcq")]
    partial class AddTopicMaterialMcq
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearningPlatform.Models.MasterCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mname");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createdBy");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("mstatus");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mthumbnail");

                    b.HasKey("Id");

                    b.ToTable("Master_course");
                });

            modelBuilder.Entity("LearningPlatform.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("material_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assignment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("assignment");

                    b.Property<int>("MasterCourseId")
                        .HasColumnType("int")
                        .HasColumnName("mid");

                    b.Property<int>("SubCourseId")
                        .HasColumnType("int")
                        .HasColumnName("sid");

                    b.Property<int>("TopicId")
                        .HasColumnType("int")
                        .HasColumnName("tid");

                    b.HasKey("Id");

                    b.HasIndex("MasterCourseId");

                    b.HasIndex("SubCourseId");

                    b.HasIndex("TopicId");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("LearningPlatform.Models.Mcq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mcqid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question");

                    b.Property<int>("TopicId")
                        .HasColumnType("int")
                        .HasColumnName("tid");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Mcq");
                });

            modelBuilder.Entity("LearningPlatform.Models.SubCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("samount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createdBy");

                    b.Property<int>("MasterCourseId")
                        .HasColumnType("int")
                        .HasColumnName("mid");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("sstatus");

                    b.Property<string>("SubCourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sname");

                    b.HasKey("Id");

                    b.HasIndex("MasterCourseId");

                    b.ToTable("sub_course");
                });

            modelBuilder.Entity("LearningPlatform.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MasterCourseId")
                        .HasColumnType("int")
                        .HasColumnName("mid");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("tstatus");

                    b.Property<int>("SubCourseId")
                        .HasColumnType("int")
                        .HasColumnName("sid");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tthumbnail");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tname");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("videoUrl");

                    b.HasKey("Id");

                    b.HasIndex("MasterCourseId");

                    b.HasIndex("SubCourseId");

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("LearningPlatform.Models.Material", b =>
                {
                    b.HasOne("LearningPlatform.Models.MasterCourse", "MasterCourse")
                        .WithMany()
                        .HasForeignKey("MasterCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningPlatform.Models.SubCourse", "SubCourse")
                        .WithMany()
                        .HasForeignKey("SubCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningPlatform.Models.Topic", "Topic")
                        .WithMany("Materials")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterCourse");

                    b.Navigation("SubCourse");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("LearningPlatform.Models.Mcq", b =>
                {
                    b.HasOne("LearningPlatform.Models.Topic", "Topic")
                        .WithMany("Mcqs")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("LearningPlatform.Models.SubCourse", b =>
                {
                    b.HasOne("LearningPlatform.Models.MasterCourse", "MasterCourse")
                        .WithMany("SubCourses")
                        .HasForeignKey("MasterCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterCourse");
                });

            modelBuilder.Entity("LearningPlatform.Models.Topic", b =>
                {
                    b.HasOne("LearningPlatform.Models.MasterCourse", "MasterCourse")
                        .WithMany()
                        .HasForeignKey("MasterCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningPlatform.Models.SubCourse", "SubCourse")
                        .WithMany()
                        .HasForeignKey("SubCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterCourse");

                    b.Navigation("SubCourse");
                });

            modelBuilder.Entity("LearningPlatform.Models.MasterCourse", b =>
                {
                    b.Navigation("SubCourses");
                });

            modelBuilder.Entity("LearningPlatform.Models.Topic", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("Mcqs");
                });
#pragma warning restore 612, 618
        }
    }
}
