// <auto-generated />
using System;
using ELearning.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ELearning.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260902174337_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ELearning.Models.AdminSubscription", b =>
                {
                    b.Property<int>("SubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sub_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubId"));

                    b.Property<int>("Mid")
                        .HasColumnType("int")
                        .HasColumnName("mid");

                    b.Property<int>("Sid")
                        .HasColumnType("int")
                        .HasColumnName("sid");

                    b.Property<decimal>("SubAmount")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("sub_amount");

                    b.Property<string>("SubStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subStatus");

                    b.Property<string>("SubThumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subThumbnail");

                    b.Property<string>("SubType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sub_type");

                    b.HasKey("SubId");

                    b.ToTable("AdminSubscription");
                });

            modelBuilder.Entity("ELearning.Models.MasterCourse", b =>
                {
                    b.Property<int>("Mid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mid"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createdBy");

                    b.Property<string>("Mname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mname");

                    b.Property<string>("Mstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mstatus");

                    b.Property<string>("Mthumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mthumbnail");

                    b.HasKey("Mid");

                    b.ToTable("Master_course");
                });

            modelBuilder.Entity("ELearning.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("material_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<string>("Assignment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("assignment");

                    b.Property<int>("Mid")
                        .HasColumnType("int")
                        .HasColumnName("mid");

                    b.Property<int>("Sid")
                        .HasColumnType("int")
                        .HasColumnName("sid");

                    b.Property<int>("Tid")
                        .HasColumnType("int")
                        .HasColumnName("tid");

                    b.HasKey("MaterialId");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("ELearning.Models.Mcq", b =>
                {
                    b.Property<int>("Msqid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("msqid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Msqid"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question");

                    b.Property<int>("Tid")
                        .HasColumnType("int")
                        .HasColumnName("tid");

                    b.HasKey("Msqid");

                    b.ToTable("Mcq");
                });

            modelBuilder.Entity("ELearning.Models.MyCourses", b =>
                {
                    b.Property<int>("Sid")
                        .HasColumnType("int")
                        .HasColumnName("sid");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Sid", "UserId");

                    b.ToTable("my_courses");
                });

            modelBuilder.Entity("ELearning.Models.SubCourse", b =>
                {
                    b.Property<int>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sid"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createdBy");

                    b.Property<int>("Mid")
                        .HasColumnType("int")
                        .HasColumnName("mid");

                    b.Property<decimal>("Samount")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("samount");

                    b.Property<string>("Sname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sname");

                    b.Property<string>("Sstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sstatus");

                    b.HasKey("Sid");

                    b.ToTable("sub_course");
                });

            modelBuilder.Entity("ELearning.Models.Topic", b =>
                {
                    b.Property<int>("Tid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Tid"));

                    b.Property<int>("Mid")
                        .HasColumnType("int")
                        .HasColumnName("mid");

                    b.Property<int>("Sid")
                        .HasColumnType("int")
                        .HasColumnName("sid");

                    b.Property<string>("Tname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tname");

                    b.Property<string>("Tstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tstatus");

                    b.Property<string>("Tthumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tthumbnail");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("videoUrl");

                    b.HasKey("Tid");

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("ELearning.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_email");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_password");

                    b.HasKey("UserId");

                    b.ToTable("user");
                });
#pragma warning restore 612, 618
        }
    }
}
